"""replace contract fields with blockchain fields

Revision ID: 19bca6efd015
Revises: 
Create Date: 2025-11-08 19:20:05.647227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bca6efd015'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('blockchain_order_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_blockchain_order_id'), 'orders', ['blockchain_order_id'], unique=False)
    op.drop_column('orders', 'escrow_tx_hash')
    op.drop_column('orders', 'contract_order_id')
    op.drop_column('orders', 'release_tx_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('release_tx_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('contract_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('escrow_tx_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_blockchain_order_id'), table_name='orders')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'blockchain_tx_hash')
    op.drop_column('orders', 'blockchain_order_id')
    # ### end Alembic commands ###
